#!/bin/bash

# Define the destination and remote server details
REMOTE_USER="wisnu"
REMOTE_HOST="192.168.225.2"
REMOTE_PATH="/mnt/trusmicorp/rspproject/assets/"

# Define the source path
SOURCE_PATH="/var/www/html/rspproject/assets/"

# List of files and directories to sync
FILES=(
    "404"
    "amchartjs"
    "apex_chart"
    "barcode"
    "berkas_bic"
    "bootstrap-icons"
    "bower_components"
    "clik"
    "css"
    "datatables"
    "datatables.net"
    "datepicker"
    "datetimepicker"
    "dist"
    "dropify"
    "edit-table"
    "echarts"
    "fancybox"
    "font_awesome"
    "fontawesome"
    "fonts"
    "foto_activity_sales"
    "foto_drafter"
    "foto_gci"
    "foto_kunci"
    "foto_lahan_baru"
    "foto_lumpur_test"
    "foto_plat_bangun"
    "foto_project"
    "gif"
    "hasil_ukur_lahan"
    "icon"
    "images"
    "invoice"
    "jaminan_sph"
    "jquery-offcanvas"
    "jquery-ui-1.13.2"
    "js"
    "jspdf"
    "jvectormap"
    "klausul"
    "loader_loading.gif"
    "locales"
    "loading"
    "logo"
    "nota_distribusi"
    "nota_penjualan"
    "pages"
    "pcassets"
    "pdf"
    "pdf_js"
    "pdf_rinci_old"
    "ppjb"
    "print.css"
    "project_update"
    "rangeslider-2.3.0"
    "responsive"
    "sbum"
    "scss"
    "select2"
    "semantic"
    "slimselect"
    "soft_delete"
    "spk_temp"
    "spmk"
    "summernote"
    "summernote-0.8.18-dist"
    "sweetalert"
    "tasklist_area_spv"
    "tasklist_estate"
    "timeline"
    "toogle-switch"
    "treeDataJs"
    "treeMaker"
    "upload_breakdown"
    "upload_spk"
    # "uploads"
    "user"
    "vendor"


)

# Loop through each file/directory and sync it
for ITEM in "${FILES[@]}"; do
    echo "Syncing $ITEM to $REMOTE_HOST:$REMOTE_PATH"
    rsync -avz --progress "$SOURCE_PATH$ITEM" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
done

echo "All files have been synchronized."
