#!/bin/bash

# Define the destination and remote server details
REMOTE_USER="wisnu"
REMOTE_HOST="192.168.225.2"
REMOTE_PATH="/mnt/trusmicorp/"

# Define the source path
SOURCE_PATH="/var/www/html/"

# List of files and directories to sync
FILES=(
    "api_chatbot"
    #"daily_checklist.tar.gz"
    "e-catalog"
    "grab_online"
    "main"
    "push"
    "spop"
    #"todo_backup_07-09-22.zip"
    "apk"
    #"dashboard_bt_store.old.move_to_btbatikcorp.com.zip"
    #"e-catalog_old"
    "hr"
    "mbti"
    "pushn"
    #"spop.zip"
    #"TrusmiOnTime.zip"
    "aplikasi_absen"
    #"dashboard_bt_store.zip"
    "em"
    "html"
    "media"
    "pytrends"
    "system"
    "update_member"
    "b_upload"
    "dashboard_rsp"
    "e-training"
    "index.html"
    "mom_new.zip"
    "readme.rst"
    "tbns-small.png"
    "upup.sw.min.js"
    "ceo"
    "dash_ceo"
    "feedback_temuan"
   #"index.old.html"
    #"mom.zip"
    "robots.txt"
    "TEMA"
    "url.html"
    "Chatbot"
    #"dash_fbt_old.zip"
    #"feedback_temuan_old"
    "index.php"
    "notify"
    "rsp"
    "temuan_progres"
    "user_guide"
    "chat.html"
    #"dash_fbt.zip"
    "files"
    #"infoo_php.php"
    #"nugie.jpg"
    "rsp_ocr"
   # "test_camera"
    "visit_pesona"
    "CODE_OF_CONDUCT.md"
    "dash.zip"
    "finance"
    "katalog"
    "od"
    #"rspproject"
    #"test.pdf"
    "wankreb.jpg"
    "composer.json"
    "devkit"
    "finance_bali"
    "katalog_240910"
    "pdf"
    "rspstatus"
    #"test.php"
    "wfh"
    #"contributing.md"
    "disc"
    "finance_fbt"
    #"katalog_bckp"
    "pdf_rinci"
    "sentimen"
    "test_rn_360"
    #"WinSCP.ini"
    "crt.html"
    "disc_id"
    "finance_rsp"
    #"katalog_kania"
    "personaliti.jpeg"
    "siska"
    #"thekeranjang_pos.zip"
    "ws_chat"
    "curl.php"
    "dokumentasi_developer"
    "fprint.php"
    "kwitansi"
    "pobox"
    "pslog.txt"
    "sitemap.xml"
    "ticket.zip"
    "ziFM7G2k"
    "customer"
    "eaf"
    "google34143705fcd23a23.html"
    "license.txt"
    "sop"
    "tiu"
    "zilbqPBS rapih ini"
)

# Loop through each file/directory and sync it
for ITEM in "${FILES[@]}"; do
    echo "Syncing $ITEM to $REMOTE_HOST:$REMOTE_PATH"
    rsync -avz --progress "$SOURCE_PATH$ITEM" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
done

echo "All files have been synchronized."
