#!/bin/bash

# Define the destination and remote server details
REMOTE_USER="wisnu"
REMOTE_HOST="192.168.225.2"
REMOTE_PATH="/mnt/trusmicorp/rspproject/assets/uploads/"

# Define the source path
SOURCE_PATH="/mnt/localpool/media/uploads/"

# List of files and directories to sync
FILES=(
    "admin_collect"
    "after_sales"
    "agreement"
    "ardajam"
    "awareness"
    "ba_perbaikan"
    "ba_sertifikat"
    "ba_sistem"
    "bast"
    "berkas_bic"
    "bestek"
    "biaya_proses"
    "boq"
    "bprhik"
    "briefing"
    "bukti_klaim"
    "ceklis_rumah"
    "chat_bm"
    "co_co"
    "collection"
    "eaf"
    "eaf110e57e437_new.pdf"
    "files"
    "files_memo"
    "footer-ba.png"
    "foto_artesis"
    "gambar_kerja"
    "grab_posting"
    "hammer_test"
    "header-ba.png"
    "header-cas.png"
    "header-dawuan.png"
    "header-rsp2.png"
    "header-rtp.png"
    "header-rtp2.png"
    "header-tss.png"
    "header-tss2.png"
    "helper_project"
    "helper_project_afs"
    "index.html"
    "infrastruktur"
    "inspeksi_audit"
    "instalasi"
    "instalasi_dev"
    "inv_infra"
    "jaminan_sph"
    "job_list"
    "ktp"
    "kyg_kpl"
    "legal"
    "listrik_air"
    "logo_rsp.jpg"
    "logotrusmi2.png"
    "mep"
    "mkt_prob"
    "nota_tagihan"
    "npwp"
    "opname_rakon"
    "pdam"
    "pendampingan"
    "pengecekan"
    "pengecekan_garansi"
    "pengecekanfoto_1240404141440.jpg"
    "pengecekanfoto_1240404142048.jpg"
    "pengecekanfoto_1240404142127.jpg"
    "pengecekanfoto_1240404143055.jpg"
    "pengecekanfoto_1240404143317.jpg"
    "pengecekanfoto_1240404143620.jpg"
    "pengecekanfoto_1240404144621.jpg"
    "pengecekanfoto_1240404145158.jpg"
    "pengecekanfoto_5240404143118.jpg"
    "pengecekanlampiran_1240404140953."
    "pengecekanlampiran_1240404141031.jpg"
    "pengawasan"
    "pengawasan_dev"
    "pengawasan_inf"
    "pengurugan"
    "pengurugan_mobile"
    "perbaikan"
    "plan_infra"
    "posting_sosmed"
    "postingan_sosmedTL-AWN-3-subsidi.jpg"
    "pov_surat_jalan"
    "ppjb"
    "problem_solving"
    "progres"
    "promo_em"
    "psu"
    "punya_rumah"
    "reject_aftersales"
    "reveral"
    "rsp_ocr"
    "sales_counter"
    "sidak_qc"
    "site_plan"
    "siteplan_svg"
    "sk_manfaat"
    "spk_instalasi"
    "spr_digital"
    "stp"
    "standar"
    "sync.ffs_db"
    "sync.ffs_lock"
    "tasklist_pelaksana"
    "tasklist_pelaksana_2022"
    "tasklist_perbaikan"
    "tasklist_surveyor"
    "temuan"
    "temuan_audit"
    "temuan_audit_new"
    "terima_kunci"
    "vendor"



)

# Loop through each file/directory and sync it
for ITEM in "${FILES[@]}"; do
    echo "Syncing $ITEM to $REMOTE_HOST:$REMOTE_PATH"
    rsync -avz --progress "$SOURCE_PATH$ITEM" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
done

echo "All files have been synchronized."